[package]
name = "bridge"
version = "0.1.0"

[dependencies]
starknet = "2.6.3"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.14.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.23.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[lib]

[tool.sncast.katana]
account = "katana_account"
url = "http://127.0.0.1:5050"
